name: Deploy to GAS

on:
  push:
    branches: [ master ]

env:
  ACCESS_TOKEN: ${{ secrets.GAS_ACCESS_TOKEN }}
  ID_TOKEN: ${{ secrets.GAS_ID_TOKEN }}
  REFRESH_TOKEN: ${{ secrets.GAS_REFRESH_TOKEN }}
  CLIENT_ID: ${{ secrets.GAS_CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.GAS_CLIENT_SECRET }}
  SCRIPT_ID: ${{ secrets.GAS_SCRIPT_ID }}

jobs:
  merged-action:
    runs-on: ubuntu-latest
    steps:
    - name: pull
      uses: actions/checkout@master

    - name: Node Install
      run: | 
        sudo apt install nodejs
        sudo apt install npm
    - name: clasp install
      run: sudo npm i @google/clasp -g

    - name: generate clasprc.json
      run: |
        sudo sed -i -e "s/\"access_token\":\"dummy\"/\"access_token\":\"${GAS_ACCESS_TOKEN}\"/" clasprc.json
        sudo sed -i -e "s/\"id_token\":\"dummy\"/\"id_token\":\"${GAS_ID_TOKEN}\"/" clasprc.json
        sudo sed -i -e "s/\"clientId\":\"dummy\"/\"clientId\":\"${GAS_CLIENT_ID}\"/" clasprc.json
        sudo sed -i -e "s/\"clientSecret\":\"dummy\"/\"clientSecret\":\"${GAS_CLIENT_SECRET}\"/" clasprc.json
        sudo sed -i -e "s@\"refresh_token\":\"dummy\"@\"refresh_token\":\"${GAS_REFRESH_TOKEN}\"@" clasprc.json

    - name: set clasprc
      run: sudo cat clasprc.json > ~/.clasprc.json

    - name: push
      run: sudo clasp push --force
    
    - name: deploy
      run: sudo clasp deploy